# data_path folder definition
data_path = ".\data\\"
output_path = data_path + "output\\"


def dataframe_to_csv(tweets_df):
    """
    It takes dataframe and stored in to a csv file
    :param tweets_df: imported dataframe has be passed as argument
    :rtype: object csv file is created in data_path folder
    """
    output_csv = data_path + 'twitter_processed.csv'
    tweets_df.to_csv(output_csv, encoding='utf-8', index=False)


def wc_to_file(wordcloud, cluster):
    """
    It takes wordcloud and cluster related and store it into a png file. File name indicates the cluster for
    the wordcloud
    :param cluster: Cluster passed as argument. It is an int object in dataframe
    :param wordcloud: wordcloud generated for the given cluster. It can be generated by generate_wc() function
    :rtype: object png file is created in output_path folder
    """
    wordcloud.to_file(output_path + 'cluster{}.png'.format(cluster))


def hist_to_file(plot, cluster):
    """
    It takes plot and cluster related and store it into a png file. File name indicates the cluster for the plot
    :param cluster: Cluster passed as argument. It is an int object in dataframe
    :param plot: plot generated has be passed as argument. It can be generated by generate_wf_hist() function
    :rtype: object csv file is created in data_path folder
    """
    plot.savefig(output_path + "word_frequencies{}.png".format(cluster))
